title: Luis Contreras Blog
author: Obsinqsob01
email: luisguerra495@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog from Luis Contreras, created following the course of Github Lab.

# social links
twitter_username: ellcontreras
github_username:  Obsinqsob01

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
